portus: added Docker secrets support
Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>

diff --git a/derived_images/portus/init b/derived_images/portus/init
--- a/derived_images/portus/init
+++ b/derived_images/portus/init
@@ -49,6 +49,34 @@ setup_database() {
   set -e
 }
 
+# Usage: file_env 'XYZ_DB_PASSWORD' 'example'. This code is taken from:
+# https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh
+file_env() {
+    local var="$1"
+    local fileVar="${var}_FILE"
+    local def="${2:-}"
+    if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
+        echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
+        exit 1
+    fi
+    local val="$def"
+    if [ "${!var:-}" ]; then
+        val="${!var}"
+    elif [ "${!fileVar:-}" ]; then
+        val="$(< "${!fileVar}")"
+    fi
+    export "$var"="$val"
+    unset "$fileVar"
+}
+
+# Setup environment variables from secrets.
+secrets=( PORTUS_DB_PASSWORD PORTUS_PASSWORD PORTUS_SECRET_KEY_BASE )
+for s in "${secrets[@]}"; do
+    if [[ -z "${!s}" ]]; then
+        file_env "$s"
+    fi
+done
+
 # Ensure additional certificates (e.g. docker registry) are known.
 update-ca-certificates
 
